//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinhLuong.SMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMS.SMSSoap")]
    public interface SMSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendSMS(int receiver_ID, string receiver_FullName, string receiver_TramID, string receiver_DonViID, string sender, string receiver, string content, string listPhieuBaoHongID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendStatisticSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendStatisticSMS(int receiver_ID, string HoTen, string DonViID, string TramID, int TongSoPhieu, int SoPhieuQuaHan, string receiver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendAlertSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendAlertSMS(int receiver_ID, string sender, string username, string sodienthoai, string loaidichvu, string receiver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMaskChangeSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendMaskChangeSMS(string ThueBaoID, string CommandName, string sender, int Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendDebitSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendDebitSMS(string sender, string receiver_sodienthoai, string receiver_fullname, string receiver_tram, string receiver_donvi, string content, string SendFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPortalOTPSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendPortalOTPSMS(int receiver_ID, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendBroadCastSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendBroadCastSMS(int receiver_ID, string receiver_FullName, string receiver_TramID, string receiver_DonViID, string sender, string receiver, string content, string UuTien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSGiaoPhatTrien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendSMSGiaoPhatTrien(int receiver_ID, string receiver_FullName, string receiver_TramID, string receiver_DonViID, string sender, string receiver, string UserName, string SoDienThoai, string LoaiDichVu, string ThoiHan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendAlertSalary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendAlertSalary(int thang, int kyluong, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendAlertSalaryExt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendAlertSalaryExt(int nam, int thang, int loai, string diengiai, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSAlertReportSys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendSMSAlertReportSys(string UserName, string smsBody, string sender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSAlertLimiPrepay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendSMSAlertLimiPrepay(string username, string sodienthoai, string loaidichvu, string sender, string smsContent);
        
        // CODEGEN: Parameter 'ListPhoneNumber' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOptionSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TinhLuong.SMS.SendOptionSMSResponse SendOptionSMS(TinhLuong.SMS.SendOptionSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSBy993", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendSMSBy993(string receiver_sodienthoai, string content);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PeopleReceived : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string soDienThoaiField;
        
        private string hoTenField;
        
        private string smsContentField;
        
        private string donViIDField;
        
        private string tramIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SoDienThoai {
            get {
                return this.soDienThoaiField;
            }
            set {
                this.soDienThoaiField = value;
                this.RaisePropertyChanged("SoDienThoai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string HoTen {
            get {
                return this.hoTenField;
            }
            set {
                this.hoTenField = value;
                this.RaisePropertyChanged("HoTen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string smsContent {
            get {
                return this.smsContentField;
            }
            set {
                this.smsContentField = value;
                this.RaisePropertyChanged("smsContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DonViID {
            get {
                return this.donViIDField;
            }
            set {
                this.donViIDField = value;
                this.RaisePropertyChanged("DonViID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TramID {
            get {
                return this.tramIDField;
            }
            set {
                this.tramIDField = value;
                this.RaisePropertyChanged("TramID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOptionSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOptionSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PeopleReceived[] ListPhoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sender;
        
        public SendOptionSMSRequest() {
        }
        
        public SendOptionSMSRequest(PeopleReceived[] ListPhoneNumber, string sender) {
            this.ListPhoneNumber = ListPhoneNumber;
            this.sender = sender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOptionSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOptionSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendOptionSMSResult;
        
        public SendOptionSMSResponse() {
        }
        
        public SendOptionSMSResponse(int SendOptionSMSResult) {
            this.SendOptionSMSResult = SendOptionSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSSoapChannel : TinhLuong.SMS.SMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSSoapClient : System.ServiceModel.ClientBase<TinhLuong.SMS.SMSSoap>, TinhLuong.SMS.SMSSoap {
        
        public SMSSoapClient() {
        }
        
        public SMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SendSMS(int receiver_ID, string receiver_FullName, string receiver_TramID, string receiver_DonViID, string sender, string receiver, string content, string listPhieuBaoHongID) {
            return base.Channel.SendSMS(receiver_ID, receiver_FullName, receiver_TramID, receiver_DonViID, sender, receiver, content, listPhieuBaoHongID);
        }
        
        public int SendStatisticSMS(int receiver_ID, string HoTen, string DonViID, string TramID, int TongSoPhieu, int SoPhieuQuaHan, string receiver) {
            return base.Channel.SendStatisticSMS(receiver_ID, HoTen, DonViID, TramID, TongSoPhieu, SoPhieuQuaHan, receiver);
        }
        
        public int SendAlertSMS(int receiver_ID, string sender, string username, string sodienthoai, string loaidichvu, string receiver) {
            return base.Channel.SendAlertSMS(receiver_ID, sender, username, sodienthoai, loaidichvu, receiver);
        }
        
        public bool SendMaskChangeSMS(string ThueBaoID, string CommandName, string sender, int Type) {
            return base.Channel.SendMaskChangeSMS(ThueBaoID, CommandName, sender, Type);
        }
        
        public bool SendDebitSMS(string sender, string receiver_sodienthoai, string receiver_fullname, string receiver_tram, string receiver_donvi, string content, string SendFrom) {
            return base.Channel.SendDebitSMS(sender, receiver_sodienthoai, receiver_fullname, receiver_tram, receiver_donvi, content, SendFrom);
        }
        
        public int SendPortalOTPSMS(int receiver_ID, string sender) {
            return base.Channel.SendPortalOTPSMS(receiver_ID, sender);
        }
        
        public bool SendBroadCastSMS(int receiver_ID, string receiver_FullName, string receiver_TramID, string receiver_DonViID, string sender, string receiver, string content, string UuTien) {
            return base.Channel.SendBroadCastSMS(receiver_ID, receiver_FullName, receiver_TramID, receiver_DonViID, sender, receiver, content, UuTien);
        }
        
        public int SendSMSGiaoPhatTrien(int receiver_ID, string receiver_FullName, string receiver_TramID, string receiver_DonViID, string sender, string receiver, string UserName, string SoDienThoai, string LoaiDichVu, string ThoiHan) {
            return base.Channel.SendSMSGiaoPhatTrien(receiver_ID, receiver_FullName, receiver_TramID, receiver_DonViID, sender, receiver, UserName, SoDienThoai, LoaiDichVu, ThoiHan);
        }
        
        public int SendAlertSalary(int thang, int kyluong, string sender) {
            return base.Channel.SendAlertSalary(thang, kyluong, sender);
        }
        
        public int SendAlertSalaryExt(int nam, int thang, int loai, string diengiai, string sender) {
            return base.Channel.SendAlertSalaryExt(nam, thang, loai, diengiai, sender);
        }
        
        public int SendSMSAlertReportSys(string UserName, string smsBody, string sender) {
          
            return base.Channel.SendSMSAlertReportSys(UserName, smsBody, sender);
        }
        
        public int SendSMSAlertLimiPrepay(string username, string sodienthoai, string loaidichvu, string sender, string smsContent) {
            return base.Channel.SendSMSAlertLimiPrepay(username, sodienthoai, loaidichvu, sender, smsContent);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TinhLuong.SMS.SendOptionSMSResponse TinhLuong.SMS.SMSSoap.SendOptionSMS(TinhLuong.SMS.SendOptionSMSRequest request) {
            return base.Channel.SendOptionSMS(request);
        }
        
        public int SendOptionSMS(PeopleReceived[] ListPhoneNumber, string sender) {
            TinhLuong.SMS.SendOptionSMSRequest inValue = new TinhLuong.SMS.SendOptionSMSRequest();
            inValue.ListPhoneNumber = ListPhoneNumber;
            inValue.sender = sender;
            TinhLuong.SMS.SendOptionSMSResponse retVal = ((TinhLuong.SMS.SMSSoap)(this)).SendOptionSMS(inValue);
            return retVal.SendOptionSMSResult;
        }
        
        public int SendSMSBy993(string receiver_sodienthoai, string content) {
            return base.Channel.SendSMSBy993(receiver_sodienthoai, content);
        }
    }
}
